### ISSUE TITLE
Allow reconnection from an IP/port to replace a session stuck in DISCONNECTING state

### ISSUE THREAD

**Issue by dktapps** [pmmp/RakLib#105]
I frequently see cases where the MCPE client improperly hangs up the connection during disconnect, leading to RakLib to refuse new connection from the same client when quickly quitting and rejoining the server. To combat this, it should be possible to have the existing session removed directly without waiting if the session was already in disconnecting state.

**Comment by markeev** [comment]
PLS, fix this shit

**Comment by pocketmineru** [comment]
Yes, i have problem.

**Comment by xDidntPot** [comment]
no

**Comment by Kyngg730** [comment]
pls fix

**Comment by gg-script** [comment]
Please fix it, this shit is very annoying

**Comment by Xterar** [comment]
fix fix go fiix

**Comment by MarcellMustafin** [comment]
pls go fix

**Comment by MrNinja008** [comment]
Yay Fox This

**Comment by xDidntPot** [comment]
looks like botted comments LOL
