### ISSUE TITLE
Typo in UnconnectedMessageHandler.php

### ISSUE THREAD

**Issue by ghost** [pmmp/RakLib#112]
I was creating a RakNet protocol handler in python and was looking for how the client GUID gets generated. While researching I came across this repository and noticed you have a typo on line #75 in UnconnectedMessageHandler.php where the function is spelt "hanlde", and should be corrected to "handle". While someone's at it, if they have time can you please tell me how the client ID gets generated as I am not familiar with php.

**Comment by dktapps** [comment]
I don't know what typo you're talking about ... it's spelled correctly on all currently active branches.

CID is just a random number. It's generated by the client, not the server.
