### ISSUE TITLE
NewIncomingConnection decode issue on iOS (10 system addresses instead of expected 20)

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/RakLib#12]
```
/NOTICE Blocked <ip address here> for 5 seconds
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #9 (): raklib\server\RakLibServer->run()
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #8 src/raklib/server/RakLibServer(235): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #7 src/raklib/server/SessionManager(109): raklib\server\SessionManager->run()
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #6 src/raklib/server/SessionManager(129): raklib\server\SessionManager->tickProcessor()
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #5 src/raklib/server/SessionManager(138): raklib\server\SessionManager->receivePacket()
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #4 src/raklib/server/SessionManager(213): raklib\server\Session->handlePacket(raklib\protocol\DATA_PACKET_4 object)
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #3 src/raklib/server/Session(540): raklib\server\Session->handleEncapsulatedPacket(raklib\protocol\EncapsulatedPacket object)
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #2 src/raklib/server/Session(406): raklib\server\Session->handleEncapsulatedPacketRoute(raklib\protocol\EncapsulatedPacket object)
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #1 src/raklib/server/Session(460): raklib\protocol\NewIncomingConnection->decode()
06.11 13:25:16 [Server] RakLibServer thread/DEBUG #0 src/raklib/protocol/NewIncomingConnection(48): raklib\protocol\Packet->getAddress(string 0.0.0.0, integer 0, integer 255)
06.11 13:25:16 [Server] RakLibServer thread/CRITICAL UnexpectedValueException: "Unknown IP address version 255" (EXCEPTION) in "src/raklib/protocol/Packet" at line 90
```

**Comment by dktapps** [comment]
beware outdated clients trying to connect to your server... pre-1.1 clients read & write 10 system addresses instead of 20. In MCPE 1.1, this was changed to 20 for reasons unknown.

**Comment by zKoz210** [comment]
i get this error on MC: BE 1.2.3 iOS 11.1, system addresses of 10 works
 good

**Comment by dktapps** [comment]
@zKoz210 can you reproduce the bug with any other device than what you stated? Every device I've tested reports 20. If you're sure you're still getting 10, then this is a Mojang bug/inconsistency.

**Comment by zKoz210** [comment]
Reproduce on all iOS devices, android seems be ok

**Comment by dktapps** [comment]
@zKoz210 what versions of iOS are your devices running?

**Comment by zKoz210** [comment]
iOS 11.1

**Comment by dktapps** [comment]
that's what I expected... I asked some other guys and this doesn't happen on 9.3, at least. So this is likely an iOS 11 specific issue with Mojang.

**Comment by zKoz210** [comment]
temp revert?

**Comment by dktapps** [comment]
This bug is specific to iOS 11, and using 10 causes undesirable behaviour on platforms other than iOS 11 (everything else reads and writes 20). I'm not reverting it for the sake of iOS 11 being a special snowflake.

**Comment by dktapps** [comment]
I'm having trouble pinning this issue down. I have one test on iOS 11.0.2 with 1.2.3 where this is working perfectly.

**Comment by ojbr** [comment]
Has someone tested if RakLibServer supports the IPv6 protocol? The device could be trying to communicate over IPv6 only

**Comment by dktapps** [comment]
No, RakLib does not support IPv6.

Although, there might be IPv6 link-local addresses in the system-addresses which aren't being decoded correctly (although I have no reason to believe that this is the case, since the IPv6 address decode works fine on everything else I've tested).

**Comment by ojbr** [comment]
That would be your reason then. iOS requires MCPE to accept communications over IPv6 on iOS to meet the app store guidelines.

**Comment by dktapps** [comment]
If the device was trying to connect over IPv6, it wouldn't be able to connect to PocketMine-MP at all, since RakLib uses a single socket on IPv4. That also doesn't explain why this happens in some cases but not others.

**Comment by ojbr** [comment]
Yeah, but some US and Canada carriers enable IPv6 as the default protocol, and have the ability to tunnel IPv4 connections with a shared UPnP port space. This usually means you cannot port forward on IPv4. This is actually enforced by Apple due to the ever dwindling availability of the IPv4 address space. The solution will still be to implement full IPv6 support

**Comment by dktapps** [comment]
> That also doesn't explain why this happens in some cases but not others.

> Reproduce on all iOS devices, android seems be ok

If this was a carrier issue, I'd expect all devices to be affected, regardless of platform.

**Comment by ojbr** [comment]
As I said, Apple are the only ones who enforce this rule as of now. Android devices in US and Canada can still use IPv4 as normal

**Comment by dktapps** [comment]
I've just tested with MCW10 and IPv6 addresses are being decoded fine (link-local addresses), so that's (probably) not the issue.

If anyone who is experiencing this issue could try connecting to dev1.ams.pmmp.io on port 19132, I have a debug setup on there.

**Comment by ojbr** [comment]
Try and force an MTU setting of 1400 rather than the default of 1492 requested by the client. This could also be an iOS issue, because it (like many wireless access points) use the first 8 bytes for a header. If that doesn't solve the issue, then I'm honestly stumped.

**Comment by LewBr** [comment]
I have the same problem, but only if the player deaths and on Win10..

**Comment by dktapps** [comment]
If anyone would like to play about with a hexdump themselves for whatever reason, here's one:
https://gist.github.com/dktapps/ccd02ca1225168ff15dcd0adc6939185

This is 100% a client bug, there are only 10 addresses in that packet.
