### ISSUE TITLE
Session still tries to send pending packets after receiving disconnect notification from client

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/RakLib#120]
### Issue description
With `xbox-auth=off` during fast rejoin player to server it will be disconnected due to already opened raklib session.

- Expected result: You can rejoin to server without any problems
- Actual result: Due to opened raklib session you can't rejoin and will be kicked until it will not be closed

### Steps to reproduce the issue
1. Join to server with not xbox client
2. Leave server
3. Rejoin fast as you can

### OS and versions
* PocketMine-MP: 676bacbee18d5eafeddf7b89ed7b70a2ce911f70
* PHP: 8.0.8
* Server OS: Ubuntu 18.04

### Backtrace or other files
https://pastebin.com/raw/DVTJRmvw

**Comment by Blackjack200** [comment]
related to https://github.com/pmmp/PocketMine-MP/issues/4369

**Comment by dktapps** [comment]
Looks like a duplicate.

**Comment by dktapps** [comment]
Fixed by e3a861187470e1facc6625040128f447ebbcbaec.
