### ISSUE TITLE
Query server broken on stable branch

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/RakLib#121]
### Issue description
https://github.com/pmmp/RakLib/commit/eb01243cbb6f2ae9aea83be64bc9c6fc8408f752 ignores the fact that packets may be received from query

### Steps to reproduce the issue
1. send query to raklib server
2. as result you will get `Ignored datagram from $address due to no session opened (0xfe)`

**Comment by Blackjack200** [comment]
https://github.com/pmmp/PocketMine-MP/blob/6a8280b1ba3c19816ca8138e65ee466468abc151/src/Server.php#L1033-L1043
