### ISSUE TITLE
IPv6 addresses can't be decoded correctly when PHP is compiled without IPv6 support

### ISSUE THREAD

**Issue by dktapps** [pmmp/RakLib#24]
The client can send IPv6 internal addresses in ID_NEW_INCOMING_CONNECTION even if the connection is over IPv4. This causes decode errors when on a PHP build without IPv6 support.

This should either:
a) make IPv6 support a requirement
b) dump addresses which are IPv6 when IPv6 is not enabled (they are a fixed length, so this shouldn't be hard)

**Comment by dschwartz783** [comment]
IPv4 depletion is a serious thing now as both IANA and ARIN have been depleted for years. It really doesn't make sense to compile anything without IPv6 support anymore. In the not too distant future, I can see it becoming a necessity. Even if PocketMine doesn't strictly need it yet, I see this as a "you'll thank me later" kind of thing. Just make it a requirement. No hacks necessary that way.
