### ISSUE TITLE
Refused Connection from x.x.x.x 50678 due to incompatible RakNet protocol version (expected 8, got 9)

### ISSUE THREAD

**Issue by DitDitGitHub** [pmmp/RakLib#31]
So, I'm trying to connect to my PMMP server, which I just port-forwarded and made into a custom-ip with www.no-ip.org, and now I get this error on the console: 

[19:41:09] [RakLibServer thread/NOTICE]: Refused connection from x.x.x.x (just blanked that out for ya, and this wasn't in the console) 50678 due to incompatible RakNet protocol version (expected 8, got 9).

And I'm thinking, `<iframe src="https://giphy.com/embed/3o7527pa7qs9kCG78A" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/nehumanesociety-funny-dog-3o7527pa7qs9kCG78A"></a></p>`

So any help would be appreciated, DitDit :).

**Comment by dktapps** [comment]
You're using an incompatible client version as the message indicates. Use the `version` command to check which client version you should be using.

**Comment by DitDitGitHub** [comment]
If version 1.5.3 is different from 1.5.0, then it should be fine.

**Comment by geNAZt** [comment]
Latest version is 1.6 not 1.5, version 9 (raknet) is a 1.6 client.
