### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by nnnlog** [pmmp/RakLib#37]
Link to crashdump:   https://pastebin.com/3p0dDKty

### Additional comments (optional)
Git commit version: 4ae6428
Ubuntu version: 18.04

When PMMP is run on WSL (Windows Subsystem for Linux), server crashes on startup with following message:
 ```socket_set_option(): unable to set socket option [22]: Invalid argument```

**Comment by dktapps** [comment]
That's a strange one really, because as far as I know REUSEADDR is disabled out of the box, and that code is simply trying to explicitly disable it. Very odd.

**Comment by dktapps** [comment]
This change was introduced in an entirely unrelated commit, typical of shoghi: https://github.com/pmmp/PocketMine-MP/commit/f1cb29cc8b0e0490d35e2ae5ac57c17160afe7c7

I do not know what he was trying to achieve with this, but the option is disabled by default on every platform I'm aware of, so it's probably safe to just remove it.

**Comment by dktapps** [comment]
I am not able to reproduce this bug on WSL with Ubuntu 18.04.1 + Windows 10 1809. Any further comments on this?

**Comment by dktapps** [comment]
never mind, seems it only appears on the latest bleeding-edge builds...
