### ISSUE TITLE
AdvertiseSystem is unused dead code

### ISSUE THREAD

**Issue by SOF3** [pmmp/RakLib#46]
There is no reason to keep something we don't use if we aren't implementing all unused packets anyway. This is inconsistent and looks confusing to people referring to RakLib as a protocol reference (which was what PocketMine was initially supposed to be).

**Comment by Frago9876543210** [comment]
By the same logic, you can delete 32 channels for encapsulated packets. Delete needACK and other not minecraft-related things.

A final decision needs to be made. This library implements basic RakNet protocol or basic minecraft server wrapper?

**Comment by SOF3** [comment]
The point is not that it's not used in PocketMine, but that it's not used in RakLib. It's OK that PocketMine doesn't need it, but if it isn't used in RakLib as well, there is no way that it could be useful.

BTW, needACK isn't something in RakNet protocol, and it is used in PocketMine.
