### ISSUE TITLE
Combine IP Address with Client ID (or something) for multiple players from same IP

### ISSUE THREAD

**Issue by drowe** [pmmp/RakLib#49]
With the packet limiting portion (possibly also related to #32) - I have 3 clients connecting to my server from the same public IP - I think the rate limiting is based on the IP only, instead of a composite key of sorts with the IP and the client.  Thus, enough activity from 3 players on the same IP - causes a server crash / IP ban with too many packets.

**Comment by dktapps** [comment]
This would make it too easy to execute denial of service attacks.

**Comment by drowe** [comment]
Surely some balance could be reached?  Say configuration for X number of clients using the same IP?

**Comment by drowe** [comment]
@dktapps - what is the expected maximum number of clients per IP address - 1 player?  Can/Should this be documented somewhere?
