### ISSUE TITLE
I cannot use PocketMine as part of 'Big server'

### ISSUE THREAD

**Issue by GamakCZ** [pmmp/RakLib#57]
Hello, I've found one bug which 'cashes' the whole server. I'm using Waterdog proxy, from which I normally redirect players to other servers (as usual), that works fine... But happend that the pocketmine server handled more packets than were allowed. So it blocked address 127.0.0.1 for 300 seconds. Also because of all the players log with ip 127.0.0.1 they weren't able to play.

- The bug occourred with only 15 players on the pocketmine server, on the whole proxy was about 30 players.

- The code which is blocking the address - https://github.com/pmmp/RakLib/blob/stable/src/server/SessionManager.php#L244

- Thread on forums - https://forums.pmmp.io/threads/raklib-is-blocking-address-without-port-check.9374/#post-70363

**Comment by dktapps** [comment]
This isn't a bug. RakLib doesn't expect to see so many clients on the same IP address, because usually this indicates denial of service. #49

**Comment by GamakCZ** [comment]
10 clients on one address?

**Comment by dktapps** [comment]
The current IP limit is 20k packets per second per IP. 10 clients shouldn't be sending that many packets anyway. I'd expect a fraction of that.

**Comment by lukeeey** [comment]
Would it be possible in a plugin to change this behavior?

**Comment by dktapps** [comment]
On PM3, no, this behaviour can't currently be changed.

**Comment by TobiasG-DE** [comment]
I wrote a Plugin that changes the maximum Value using Reflection, I'll provide a link to it in a second

**Comment by TobiasG-DE** [comment]
https://github.com/lukeeey/WaterdogPM/blob/master/src/lukeeey/waterdog/Main.php This was made together with @lukeeey and fixed the issue for me, although it's still a hacky thing

**Comment by dktapps** [comment]
if someone wants to make a PR to the `next-minor` branch to add a `setPacketLimit` API method to `RakLibInterface` I would accept it provided it's properly done.

**Comment by lukeeey** [comment]
I actually completely forgot we made that plugin lol @TobiasG-DE

**Comment by dktapps** [comment]
please don't engage in frivolous discussion on the issue tracker.
